// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: headers.proto

package pbtypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckTypes int32

const (
	AckTypes_SYN     AckTypes = 0
	AckTypes_ACK_PSH AckTypes = 1
)

// Enum value maps for AckTypes.
var (
	AckTypes_name = map[int32]string{
		0: "SYN",
		1: "ACK_PSH",
	}
	AckTypes_value = map[string]int32{
		"SYN":     0,
		"ACK_PSH": 1,
	}
)

func (x AckTypes) Enum() *AckTypes {
	p := new(AckTypes)
	*p = x
	return p
}

func (x AckTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_headers_proto_enumTypes[0].Descriptor()
}

func (AckTypes) Type() protoreflect.EnumType {
	return &file_headers_proto_enumTypes[0]
}

func (x AckTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckTypes.Descriptor instead.
func (AckTypes) EnumDescriptor() ([]byte, []int) {
	return file_headers_proto_rawDescGZIP(), []int{0}
}

type ReqTypes int32

const (
	ReqTypes_PUSH_OBJ      ReqTypes = 0
	ReqTypes_NEXT_GROUP    ReqTypes = 1
	ReqTypes_NO_NEXT_GROUP ReqTypes = 2
	ReqTypes_RESEND_CHUNK  ReqTypes = 3
)

// Enum value maps for ReqTypes.
var (
	ReqTypes_name = map[int32]string{
		0: "PUSH_OBJ",
		1: "NEXT_GROUP",
		2: "NO_NEXT_GROUP",
		3: "RESEND_CHUNK",
	}
	ReqTypes_value = map[string]int32{
		"PUSH_OBJ":      0,
		"NEXT_GROUP":    1,
		"NO_NEXT_GROUP": 2,
		"RESEND_CHUNK":  3,
	}
)

func (x ReqTypes) Enum() *ReqTypes {
	p := new(ReqTypes)
	*p = x
	return p
}

func (x ReqTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_headers_proto_enumTypes[1].Descriptor()
}

func (ReqTypes) Type() protoreflect.EnumType {
	return &file_headers_proto_enumTypes[1]
}

func (x ReqTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqTypes.Descriptor instead.
func (ReqTypes) EnumDescriptor() ([]byte, []int) {
	return file_headers_proto_rawDescGZIP(), []int{1}
}

type SynClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mtu uint32 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
}

func (x *SynClient) Reset() {
	*x = SynClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_headers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SynClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynClient) ProtoMessage() {}

func (x *SynClient) ProtoReflect() protoreflect.Message {
	mi := &file_headers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynClient.ProtoReflect.Descriptor instead.
func (*SynClient) Descriptor() ([]byte, []int) {
	return file_headers_proto_rawDescGZIP(), []int{0}
}

func (x *SynClient) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SynClient) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type AckServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId uint64   `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Type  AckTypes `protobuf:"varint,2,opt,name=type,proto3,enum=headers.AckTypes" json:"type,omitempty"`
}

func (x *AckServer) Reset() {
	*x = AckServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_headers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckServer) ProtoMessage() {}

func (x *AckServer) ProtoReflect() protoreflect.Message {
	mi := &file_headers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckServer.ProtoReflect.Descriptor instead.
func (*AckServer) Descriptor() ([]byte, []int) {
	return file_headers_proto_rawDescGZIP(), []int{1}
}

func (x *AckServer) GetReqId() uint64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *AckServer) GetType() AckTypes {
	if x != nil {
		return x.Type
	}
	return AckTypes_SYN
}

type ReqClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type ReqTypes `protobuf:"varint,2,opt,name=type,proto3,enum=headers.ReqTypes" json:"type,omitempty"`
}

func (x *ReqClient) Reset() {
	*x = ReqClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_headers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqClient) ProtoMessage() {}

func (x *ReqClient) ProtoReflect() protoreflect.Message {
	mi := &file_headers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqClient.ProtoReflect.Descriptor instead.
func (*ReqClient) Descriptor() ([]byte, []int) {
	return file_headers_proto_rawDescGZIP(), []int{2}
}

func (x *ReqClient) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqClient) GetType() ReqTypes {
	if x != nil {
		return x.Type
	}
	return ReqTypes_PUSH_OBJ
}

type ReqServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId uint64   `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Type  ReqTypes `protobuf:"varint,2,opt,name=type,proto3,enum=headers.ReqTypes" json:"type,omitempty"`
}

func (x *ReqServer) Reset() {
	*x = ReqServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_headers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqServer) ProtoMessage() {}

func (x *ReqServer) ProtoReflect() protoreflect.Message {
	mi := &file_headers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqServer.ProtoReflect.Descriptor instead.
func (*ReqServer) Descriptor() ([]byte, []int) {
	return file_headers_proto_rawDescGZIP(), []int{3}
}

func (x *ReqServer) GetReqId() uint64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *ReqServer) GetType() ReqTypes {
	if x != nil {
		return x.Type
	}
	return ReqTypes_PUSH_OBJ
}

type PshClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId uint64 `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
}

func (x *PshClient) Reset() {
	*x = PshClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_headers_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PshClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PshClient) ProtoMessage() {}

func (x *PshClient) ProtoReflect() protoreflect.Message {
	mi := &file_headers_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PshClient.ProtoReflect.Descriptor instead.
func (*PshClient) Descriptor() ([]byte, []int) {
	return file_headers_proto_rawDescGZIP(), []int{4}
}

func (x *PshClient) GetReqId() uint64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

type FinClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FinClient) Reset() {
	*x = FinClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_headers_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinClient) ProtoMessage() {}

func (x *FinClient) ProtoReflect() protoreflect.Message {
	mi := &file_headers_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinClient.ProtoReflect.Descriptor instead.
func (*FinClient) Descriptor() ([]byte, []int) {
	return file_headers_proto_rawDescGZIP(), []int{5}
}

func (x *FinClient) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_headers_proto protoreflect.FileDescriptor

var file_headers_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0x2d, 0x0a, 0x09, 0x53, 0x79, 0x6e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x22, 0x49, 0x0a, 0x09, 0x41, 0x63, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x42, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x49, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x22, 0x0a, 0x09, 0x50, 0x73, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x72, 0x65, 0x71, 0x49, 0x64, 0x22, 0x1b, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x2a, 0x20, 0x0a, 0x08, 0x41, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x07,
	0x0a, 0x03, 0x53, 0x59, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x43, 0x4b, 0x5f, 0x50,
	0x53, 0x48, 0x10, 0x01, 0x2a, 0x4d, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x12, 0x0c, 0x0a, 0x08, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x4f, 0x42, 0x4a, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x4e, 0x45, 0x58, 0x54, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x01, 0x12, 0x11,
	0x0a, 0x0d, 0x4e, 0x4f, 0x5f, 0x4e, 0x45, 0x58, 0x54, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x43, 0x48, 0x55, 0x4e,
	0x4b, 0x10, 0x03, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x65, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x39, 0x37, 0x2f, 0x66, 0x69, 0x6c, 0x65,
	0x2d, 0x73, 0x79, 0x6e, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d,
	0x31, 0x2f, 0x70, 0x62, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_headers_proto_rawDescOnce sync.Once
	file_headers_proto_rawDescData = file_headers_proto_rawDesc
)

func file_headers_proto_rawDescGZIP() []byte {
	file_headers_proto_rawDescOnce.Do(func() {
		file_headers_proto_rawDescData = protoimpl.X.CompressGZIP(file_headers_proto_rawDescData)
	})
	return file_headers_proto_rawDescData
}

var file_headers_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_headers_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_headers_proto_goTypes = []interface{}{
	(AckTypes)(0),     // 0: headers.AckTypes
	(ReqTypes)(0),     // 1: headers.ReqTypes
	(*SynClient)(nil), // 2: headers.SynClient
	(*AckServer)(nil), // 3: headers.AckServer
	(*ReqClient)(nil), // 4: headers.ReqClient
	(*ReqServer)(nil), // 5: headers.ReqServer
	(*PshClient)(nil), // 6: headers.PshClient
	(*FinClient)(nil), // 7: headers.FinClient
}
var file_headers_proto_depIdxs = []int32{
	0, // 0: headers.AckServer.type:type_name -> headers.AckTypes
	1, // 1: headers.ReqClient.type:type_name -> headers.ReqTypes
	1, // 2: headers.ReqServer.type:type_name -> headers.ReqTypes
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_headers_proto_init() }
func file_headers_proto_init() {
	if File_headers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_headers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SynClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_headers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_headers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_headers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_headers_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PshClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_headers_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_headers_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_headers_proto_goTypes,
		DependencyIndexes: file_headers_proto_depIdxs,
		EnumInfos:         file_headers_proto_enumTypes,
		MessageInfos:      file_headers_proto_msgTypes,
	}.Build()
	File_headers_proto = out.File
	file_headers_proto_rawDesc = nil
	file_headers_proto_goTypes = nil
	file_headers_proto_depIdxs = nil
}
